CREATE DATABASE testdb;
GO

Use testdb;
GO

CREATE SCHEMA testschema;
GO

CREATE TABLE testschema.location (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  ImageURL NVARCHAR(256) NOT NULL,
  CityName NVARCHAR(50) NOT NULL,
  CountryName NVARCHAR(50) NOT NULL
);
GO

INSERT INTO testschema.location (ImageURL, CityName, CountryName) VALUES
(N'https://www.randomlists.com/img/world-city-maps/pune_india.png', N'Pune', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/hong_kong_china.png', N'Hong Kong', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/jakarta_indonesia.png', N'Jakarta', N'Indonesia'), 
(N'https://www.randomlists.com/img/world-city-maps/dhaka_bangladesh.png', N'Dhaka', N'Bangladesh'), 
(N'https://www.randomlists.com/img/world-city-maps/cairo_egypt.png', N'Cairo', N'Egypt'), 
(N'https://www.randomlists.com/img/world-city-maps/nairobi_kenya.png', N'Nairobi', N'Kenya'), 
(N'https://www.randomlists.com/img/world-city-maps/bangkok_thailand.png', N'Bangkok', N'Thailand'), 
(N'https://www.randomlists.com/img/world-city-maps/yokohama_japan.png', N'Yokohama', N'Japan'), 
(N'https://www.randomlists.com/img/world-city-maps/istanbul_turkey.png', N'Istanbul', N'Turkey'), 
(N'https://www.randomlists.com/img/world-city-maps/seoul_south_korea.png', N'Seoul', N'South Korea'), 
(N'https://www.randomlists.com/img/world-city-maps/tianjin_china.png', N'Tianjin', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/madrid_spain.png', N'Madrid', N'Spain'), 
(N'https://www.randomlists.com/img/world-city-maps/mexico_city_mexico.png', N'Mexico City', N'Mexico'), 
(N'https://www.randomlists.com/img/world-city-maps/abidjan_ivory_coast.png', N'Abidjan', N'Ivory Coast'), 
(N'https://www.randomlists.com/img/world-city-maps/kinshasa_democratic_republic_of_the_congo.png', N'Kinshasa', N'Democratic Republic of the Congo'), 
(N'https://www.randomlists.com/img/world-city-maps/hanoi_vietnam.png', N'Hanoi', N'Vietnam'), 
(N'https://www.randomlists.com/img/world-city-maps/riyadh_saudi_arabia.png', N'Riyadh', N'Saudi Arabia'), 
(N'https://www.randomlists.com/img/world-city-maps/addis_ababa_ethiopia.png', N'Addis Ababa', N'Ethiopia'), 
(N'https://www.randomlists.com/img/world-city-maps/bogota_colombia.png', N'Bogota', N'Colombia'), 
(N'https://www.randomlists.com/img/world-city-maps/new_taipei_city_republic_of_china_taiwan_.png', N'New Taipei City', N'Republic of China (Taiwan)'), 
(N'https://www.randomlists.com/img/world-city-maps/lima_peru.png', N'Lima', N'Peru'), 
(N'https://www.randomlists.com/img/world-city-maps/rio_de_janeiro_brazil.png', N'Rio de Janeiro', N'Brazil'), 
(N'https://www.randomlists.com/img/world-city-maps/moscow_russia.png', N'Moscow', N'Russia'), 
(N'https://www.randomlists.com/img/world-city-maps/durban_south_africa.png', N'Durban', N'South Africa'), 
(N'https://www.randomlists.com/img/world-city-maps/sao_paulo_brazil.png', N'Sao Paulo', N'Brazil'), 
(N'https://www.randomlists.com/img/world-city-maps/jaipur_india.png', N'Jaipur', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/lahore_pakistan.png', N'Lahore', N'Pakistan'), 
(N'https://www.randomlists.com/img/world-city-maps/alexandria_egypt.png', N'Alexandria', N'Egypt'), 
(N'https://www.randomlists.com/img/world-city-maps/hyderabad_india.png', N'Hyderabad', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/ahmedabad_india.png', N'Ahmedabad', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/santiago_chile.png', N'Santiago', N'Chile'), 
(N'https://www.randomlists.com/img/world-city-maps/shenyang_china.png', N'Shenyang', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/ankara_turkey.png', N'Ankara', N'Turkey'), 
(N'https://www.randomlists.com/img/world-city-maps/suzhou_china.png', N'Suzhou', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/surat_india.png', N'Surat', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/shenzhen_china.png', N'Shenzhen', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/cape_town_south_africa.png', N'Cape Town', N'South Africa'), 
(N'https://www.randomlists.com/img/world-city-maps/johannesburg_south_africa.png', N'Johannesburg', N'South Africa'), 
(N'https://www.randomlists.com/img/world-city-maps/berlin_germany.png', N'Berlin', N'Germany'), 
(N'https://www.randomlists.com/img/world-city-maps/shanghai_china.png', N'Shanghai', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/casablanca_moroccoa.png', N'Casablanca', N'Morocco'), 
(N'https://www.randomlists.com/img/world-city-maps/yangon_myanmar.png', N'Yangon', N'Myanmar'), 
(N'https://www.randomlists.com/img/world-city-maps/beijing_china.png', N'Beijing', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/new_york_city_united_states.png', N'New York City', N'United States'), 
(N'https://www.randomlists.com/img/world-city-maps/tokyo_japan.png', N'Tokyo', N'Japan'), 
(N'https://www.randomlists.com/img/world-city-maps/kolkata_india.png', N'Kolkata', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/karachi_pakistan.png', N'Karachi', N'Pakistan'), 
(N'https://www.randomlists.com/img/world-city-maps/los_angeles_united_states.png', N'Los Angeles', N'United States'), 
(N'https://www.randomlists.com/img/world-city-maps/jeddah_saudi_arabia.png', N'Jeddah', N'Saudi Arabia'), 
(N'https://www.randomlists.com/img/world-city-maps/saint_petersburg_russia.png', N'Saint Petersburg', N'Russia'), 
(N'https://www.randomlists.com/img/world-city-maps/baghdad_iraq.png', N'Baghdad', N'Iraq'), 
(N'https://www.randomlists.com/img/world-city-maps/singapore_singapore.png', N'Singapore', N'Singapore'), 
(N'https://www.randomlists.com/img/world-city-maps/tehran_iran.png', N'Tehran', N'Iran'), 
(N'https://www.randomlists.com/img/world-city-maps/busan_south_korea.png', N'Busan', N'South Korea'), 
(N'https://www.randomlists.com/img/world-city-maps/delhi_india.png', N'Delhi', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/chennai_india.png', N'Chennai', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/pyongyang_north_korea.png', N'Pyongyang', N'North Korea'), 
(N'https://www.randomlists.com/img/world-city-maps/bangalore_india.png', N'Bangalore', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/london_united_kingdom.png', N'London', N'United Kingdom'), 
(N'https://www.randomlists.com/img/world-city-maps/dongguan_china.png', N'Dongguan', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/guangzhou_china.png', N'Guangzhou', N'China'), 
(N'https://www.randomlists.com/img/world-city-maps/mumbai_india.png', N'Mumbai', N'India'), 
(N'https://www.randomlists.com/img/world-city-maps/ho_chi_minh_city_vietnam.png', N'Ho Chi Minh City', N'Vietnam'), 
(N'https://www.randomlists.com/img/world-city-maps/lagos_nigeria.png', N'Lagos', N'Nigeria');
GO

CREATE TABLE testschema.items (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  ImageURL NVARCHAR(256) NOT NULL,
  Name NVARCHAR(50) NOT NULL
);
GO

INSERT INTO testschema.items (ImageURL, Name) VALUES
(N'https://www.randomlists.com/img/things/soap.jpg', N'soap'), 
(N'https://www.randomlists.com/img/things/sponge.jpg', N'sponge'), 
(N'https://www.randomlists.com/img/things/television.jpg', N'television'), 
(N'https://www.randomlists.com/img/things/ring.jpg', N'ring'), 
(N'https://www.randomlists.com/img/things/tooth_picks.jpg', N'tooth picks'), 
(N'https://www.randomlists.com/img/things/nail_clippers.jpg', N'nail clippers'), 
(N'https://www.randomlists.com/img/things/checkbook.jpg', N'checkbook'), 
(N'https://www.randomlists.com/img/things/watch.jpg', N'watch'), 
(N'https://www.randomlists.com/img/things/flowers.jpg', N'flowers'), 
(N'https://www.randomlists.com/img/things/knife.jpg', N'knife'), 
(N'https://www.randomlists.com/img/things/rubber_band.jpg', N'rubber band'), 
(N'https://www.randomlists.com/img/things/bowl.jpg', N'bowl'), 
(N'https://www.randomlists.com/img/things/pants.jpg', N'pants'), 
(N'https://www.randomlists.com/img/things/keyboard.jpg', N'keyboard'), 
(N'https://www.randomlists.com/img/things/rusty_nail.jpg', N'rusty nail'), 
(N'https://www.randomlists.com/img/things/bracelet.jpg', N'bracelet'), 
(N'https://www.randomlists.com/img/things/glass.jpg', N'glass'), 
(N'https://www.randomlists.com/img/things/sofa.jpg', N'sofa'), 
(N'https://www.randomlists.com/img/things/mp3_player.jpg', N'mp3 player'), 
(N'https://www.randomlists.com/img/things/zipper.jpg', N'zipper'), 
(N'https://www.randomlists.com/img/things/drill_press.jpg', N'drill press'), 
(N'https://www.randomlists.com/img/things/cinder_block.jpg', N'cinder block'), 
(N'https://www.randomlists.com/img/things/playing_card.jpg', N'playing card'), 
(N'https://www.randomlists.com/img/things/paint_brush.jpg', N'paint brush'), 
(N'https://www.randomlists.com/img/things/book.jpg', N'book'), 
(N'https://www.randomlists.com/img/things/desk.jpg', N'desk'), 
(N'https://www.randomlists.com/img/things/nail_file.jpg', N'nail file'), 
(N'https://www.randomlists.com/img/things/clothes.jpg', N'clothes'), 
(N'https://www.randomlists.com/img/things/water_bottle.jpg', N'water bottle'), 
(N'https://www.randomlists.com/img/things/boom_box.jpg', N'boom box'), 
(N'https://www.randomlists.com/img/things/usb_drive.jpg', N'USB drive'), 
(N'https://www.randomlists.com/img/things/conditioner.jpg', N'conditioner'), 
(N'https://www.randomlists.com/img/things/pool_stick.jpg', N'pool stick'), 
(N'https://www.randomlists.com/img/things/pencil.jpg', N'pencil'), 
(N'https://www.randomlists.com/img/things/magnet.jpg', N'magnet'), 
(N'https://www.randomlists.com/img/things/blanket.jpg', N'blanket'), 
(N'https://www.randomlists.com/img/things/tomato.jpg', N'tomato'), 
(N'https://www.randomlists.com/img/things/greeting_card.jpg', N'greeting card'), 
(N'https://www.randomlists.com/img/things/rug.jpg', N'rug'), 
(N'https://www.randomlists.com/img/things/bottle_cap.jpg', N'bottle cap'), 
(N'https://www.randomlists.com/img/things/face_wash.jpg', N'face wash'), 
(N'https://www.randomlists.com/img/things/buckel.jpg', N'buckel'), 
(N'https://www.randomlists.com/img/things/wagon.jpg', N'wagon'), 
(N'https://www.randomlists.com/img/things/food.jpg', N'food'), 
(N'https://www.randomlists.com/img/things/spring.jpg', N'spring'), 
(N'https://www.randomlists.com/img/things/packing_peanuts.jpg', N'packing peanuts'), 
(N'https://www.randomlists.com/img/things/lamp.jpg', N'lamp'), 
(N'https://www.randomlists.com/img/things/tree.jpg', N'tree'), 
(N'https://www.randomlists.com/img/things/eye_liner.jpg', N'eye liner'), 
(N'https://www.randomlists.com/img/things/stop_sign.jpg', N'stop sign'), 
(N'https://www.randomlists.com/img/things/twister.jpg', N'twister'), 
(N'https://www.randomlists.com/img/things/picture_frame.jpg', N'picture frame'), 
(N'https://www.randomlists.com/img/things/bookmark.jpg', N'bookmark'), 
(N'https://www.randomlists.com/img/things/candle.jpg', N'candle'), 
(N'https://www.randomlists.com/img/things/lamp_shade.jpg', N'lamp shade'), 
(N'https://www.randomlists.com/img/things/chapter_book.jpg', N'chapter book'), 
(N'https://www.randomlists.com/img/things/purse.jpg', N'purse'), 
(N'https://www.randomlists.com/img/things/table.jpg', N'table'), 
(N'https://www.randomlists.com/img/things/street_lights.jpg', N'street lights'), 
(N'https://www.randomlists.com/img/things/chocolate.jpg', N'chocolate'), 
(N'https://www.randomlists.com/img/things/flag.jpg', N'flag'), 
(N'https://www.randomlists.com/img/things/grid_paper.jpg', N'grid paper'), 
(N'https://www.randomlists.com/img/things/soy_sauce_packet.jpg', N'soy sauce packet'), 
(N'https://www.randomlists.com/img/things/ipod.jpg', N'ipod'), 
(N'https://www.randomlists.com/img/things/eraser.jpg', N'eraser'), 
(N'https://www.randomlists.com/img/things/toothpaste.jpg', N'toothpaste'), 
(N'https://www.randomlists.com/img/things/clock.jpg', N'clock'), 
(N'https://www.randomlists.com/img/things/shovel.jpg', N'shovel'), 
(N'https://www.randomlists.com/img/things/cat.jpg', N'cat'), 
(N'https://www.randomlists.com/img/things/car.jpg', N'car'), 
(N'https://www.randomlists.com/img/things/canvas.jpg', N'canvas'), 
(N'https://www.randomlists.com/img/things/keys.jpg', N'keys'), 
(N'https://www.randomlists.com/img/things/sidewalk.jpg', N'sidewalk'), 
(N'https://www.randomlists.com/img/things/spoon.jpg', N'spoon'), 
(N'https://www.randomlists.com/img/things/glow_stick.jpg', N'glow stick'), 
(N'https://www.randomlists.com/img/things/doll.jpg', N'doll'), 
(N'https://www.randomlists.com/img/things/scotch_tape.jpg', N'scotch tape'), 
(N'https://www.randomlists.com/img/things/sand_paper.jpg', N'sand paper'), 
(N'https://www.randomlists.com/img/things/plastic_fork.jpg', N'plastic fork'), 
(N'https://www.randomlists.com/img/things/candy_wrapper.jpg', N'candy wrapper'), 
(N'https://www.randomlists.com/img/things/hair_brush.jpg', N'hair brush'), 
(N'https://www.randomlists.com/img/things/rubber_duck.jpg', N'rubber duck'), 
(N'https://www.randomlists.com/img/things/thread.jpg', N'thread'), 
(N'https://www.randomlists.com/img/things/fridge.jpg', N'fridge'), 
(N'https://www.randomlists.com/img/things/charger.jpg', N'charger'), 
(N'https://www.randomlists.com/img/things/sun_glasses.jpg', N'sun glasses'), 
(N'https://www.randomlists.com/img/things/button.jpg', N'button'), 
(N'https://www.randomlists.com/img/things/paper.jpg', N'paper'), 
(N'https://www.randomlists.com/img/things/phone.jpg', N'phone'), 
(N'https://www.randomlists.com/img/things/sticky_note.jpg', N'sticky note'), 
(N'https://www.randomlists.com/img/things/speakers.jpg', N'speakers'), 
(N'https://www.randomlists.com/img/things/sharpie.jpg', N'sharpie'), 
(N'https://www.randomlists.com/img/things/clay_pot.jpg', N'clay pot'), 
(N'https://www.randomlists.com/img/things/milk.jpg', N'milk'), 
(N'https://www.randomlists.com/img/things/air_freshener.jpg', N'air freshener'), 
(N'https://www.randomlists.com/img/things/twezzers.jpg', N'twezzers'), 
(N'https://www.randomlists.com/img/things/bottle.jpg', N'bottle'), 
(N'https://www.randomlists.com/img/things/balloon.jpg', N'balloon'), 
(N'https://www.randomlists.com/img/things/mop.jpg', N'mop'), 
(N'https://www.randomlists.com/img/things/door.jpg', N'door'), 
(N'https://www.randomlists.com/img/things/shoes.jpg', N'shoes'), 
(N'https://www.randomlists.com/img/things/tire_swing.jpg', N'tire swing'), 
(N'https://www.randomlists.com/img/things/bed.jpg', N'bed'), 
(N'https://www.randomlists.com/img/things/photo_album.jpg', N'photo album'), 
(N'https://www.randomlists.com/img/things/hanger.jpg', N'hanger'), 
(N'https://www.randomlists.com/img/things/ice_cube_tray.jpg', N'ice cube tray'), 
(N'https://www.randomlists.com/img/things/shirt.jpg', N'shirt'), 
(N'https://www.randomlists.com/img/things/apple.jpg', N'apple'), 
(N'https://www.randomlists.com/img/things/drawer.jpg', N'drawer'), 
(N'https://www.randomlists.com/img/things/washing_machine.jpg', N'washing machine'), 
(N'https://www.randomlists.com/img/things/credit_card.jpg', N'credit card'), 
(N'https://www.randomlists.com/img/things/needle.jpg', N'needle'), 
(N'https://www.randomlists.com/img/things/chair.jpg', N'chair'), 
(N'https://www.randomlists.com/img/things/leg_warmers.jpg', N'leg warmers'), 
(N'https://www.randomlists.com/img/things/mirror.jpg', N'mirror'), 
(N'https://www.randomlists.com/img/things/fake_flowers.jpg', N'fake flowers'), 
(N'https://www.randomlists.com/img/things/remote.jpg', N'remote'), 
(N'https://www.randomlists.com/img/things/carrots.jpg', N'carrots'), 
(N'https://www.randomlists.com/img/things/wallet.jpg', N'wallet'), 
(N'https://www.randomlists.com/img/things/stockings.jpg', N'stockings'), 
(N'https://www.randomlists.com/img/things/box.jpg', N'box'), 
(N'https://www.randomlists.com/img/things/vase.jpg', N'vase'), 
(N'https://www.randomlists.com/img/things/perfume.jpg', N'perfume'), 
(N'https://www.randomlists.com/img/things/bread.jpg', N'bread'), 
(N'https://www.randomlists.com/img/things/shampoo.jpg', N'shampoo'), 
(N'https://www.randomlists.com/img/things/brocolli.jpg', N'brocolli'), 
(N'https://www.randomlists.com/img/things/shawl.jpg', N'shawl'), 
(N'https://www.randomlists.com/img/things/clamp.jpg', N'clamp'), 
(N'https://www.randomlists.com/img/things/bananas.jpg', N'bananas'), 
(N'https://www.randomlists.com/img/things/pillow.jpg', N'pillow'), 
(N'https://www.randomlists.com/img/things/deodorant_.jpg', N'deodorant '), 
(N'https://www.randomlists.com/img/things/lotion.jpg', N'lotion'), 
(N'https://www.randomlists.com/img/things/tv.jpg', N'tv'), 
(N'https://www.randomlists.com/img/things/outlet.jpg', N'outlet'), 
(N'https://www.randomlists.com/img/things/lace.jpg', N'lace'), 
(N'https://www.randomlists.com/img/things/toe_ring.jpg', N'toe ring'), 
(N'https://www.randomlists.com/img/things/sandal.jpg', N'sandal'), 
(N'https://www.randomlists.com/img/things/cork.jpg', N'cork'), 
(N'https://www.randomlists.com/img/things/coasters.jpg', N'coasters'), 
(N'https://www.randomlists.com/img/things/newspaper.jpg', N'newspaper'), 
(N'https://www.randomlists.com/img/things/controller.jpg', N'controller'), 
(N'https://www.randomlists.com/img/things/monitor.jpg', N'monitor'), 
(N'https://www.randomlists.com/img/things/window.jpg', N'window'), 
(N'https://www.randomlists.com/img/things/camera.jpg', N'camera'), 
(N'https://www.randomlists.com/img/things/thermometer.jpg', N'thermometer'), 
(N'https://www.randomlists.com/img/things/slipper.jpg', N'slipper'), 
(N'https://www.randomlists.com/img/things/cup.jpg', N'cup'), 
(N'https://www.randomlists.com/img/things/model_car.jpg', N'model car'), 
(N'https://www.randomlists.com/img/things/radio.jpg', N'radio'), 
(N'https://www.randomlists.com/img/things/seat_belt.jpg', N'seat belt'), 
(N'https://www.randomlists.com/img/things/house.jpg', N'house'), 
(N'https://www.randomlists.com/img/things/sketch_pad.jpg', N'sketch pad'), 
(N'https://www.randomlists.com/img/things/key_chain.jpg', N'key chain'), 
(N'https://www.randomlists.com/img/things/puddle.jpg', N'puddle'), 
(N'https://www.randomlists.com/img/things/sailboat.jpg', N'sailboat'), 
(N'https://www.randomlists.com/img/things/thermostat.jpg', N'thermostat'), 
(N'https://www.randomlists.com/img/things/video_games.jpg', N'video games'), 
(N'https://www.randomlists.com/img/things/fork.jpg', N'fork'), 
(N'https://www.randomlists.com/img/things/truck.jpg', N'truck'), 
(N'https://www.randomlists.com/img/things/socks.jpg', N'socks'), 
(N'https://www.randomlists.com/img/things/lip_gloss.jpg', N'lip gloss'), 
(N'https://www.randomlists.com/img/things/tissue_box.jpg', N'tissue box'), 
(N'https://www.randomlists.com/img/things/bow.jpg', N'bow'), 
(N'https://www.randomlists.com/img/things/blouse.jpg', N'blouse'), 
(N'https://www.randomlists.com/img/things/pen.jpg', N'pen'), 
(N'https://www.randomlists.com/img/things/glasses.jpg', N'glasses'), 
(N'https://www.randomlists.com/img/things/soda_can.jpg', N'soda can'), 
(N'https://www.randomlists.com/img/things/screw.jpg', N'screw'), 
(N'https://www.randomlists.com/img/things/hair_tie.jpg', N'hair tie'), 
(N'https://www.randomlists.com/img/things/piano.jpg', N'piano'), 
(N'https://www.randomlists.com/img/things/floor.jpg', N'floor'), 
(N'https://www.randomlists.com/img/things/cd.jpg', N'CD'), 
(N'https://www.randomlists.com/img/things/shoe_lace.jpg', N'shoe lace'), 
(N'https://www.randomlists.com/img/things/chalk.jpg', N'chalk'), 
(N'https://www.randomlists.com/img/things/white_out.jpg', N'white out'), 
(N'https://www.randomlists.com/img/things/cookie_jar.jpg', N'cookie jar'), 
(N'https://www.randomlists.com/img/things/cell_phone.jpg', N'cell phone'), 
(N'https://www.randomlists.com/img/things/mouse_pad.jpg', N'mouse pad'), 
(N'https://www.randomlists.com/img/things/toilet.jpg', N'toilet'), 
(N'https://www.randomlists.com/img/things/headphones.jpg', N'headphones'), 
(N'https://www.randomlists.com/img/things/computer.jpg', N'computer'), 
(N'https://www.randomlists.com/img/things/towel.jpg', N'towel'), 
(N'https://www.randomlists.com/img/things/toothbrush.jpg', N'toothbrush'), 
(N'https://www.randomlists.com/img/things/teddies.jpg', N'teddies'), 
(N'https://www.randomlists.com/img/things/beef.jpg', N'beef'), 
(N'https://www.randomlists.com/img/things/helmet.jpg', N'helmet'), 
(N'https://www.randomlists.com/img/things/money.jpg', N'money'), 
(N'https://www.randomlists.com/img/things/plate.jpg', N'plate'), 
(N'https://www.randomlists.com/img/things/bag.jpg', N'bag'), 
(N'https://www.randomlists.com/img/things/couch.jpg', N'couch');
GO

CREATE TABLE testschema.measure (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  Quantity INT NOT NULL DEFAULT(1),
  Name NVARCHAR(50) NOT NULL
);
GO

INSERT INTO testschema.measure (Quantity, Name) VALUES
(1, N'each'),
(1, N'gross'),
(1, N'case'),
(1, N'kg'),
(1, N'pair'),
(1, N'gaggle (12)');
GO


CREATE TABLE testschema.employees (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  LocationID INT NOT NULL,
  Name NVARCHAR(50) NOT NULL
);
GO

INSERT INTO testschema.employees (LocationID, Name) VALUES
(33, N'Jared Tallent'),
(24, N'Nikita Khrushchev'),
(1, N'Geeta Phogat'),
(39, N'Thomas Hasler'),
(17, N'John A. MacDonald'),
(45, N'Chris Runge'),
(12, N'Michael Lessard'),
(23, N'Anthony Green'),
(20, N'Kim Li'),
(63, N'Paul Pinkney'),
(49, N'Jane Circle');
GO

CREATE TABLE testschema.customers (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  LocationID INT NOT NULL,
  Name NVARCHAR(50) NOT NULL
);
GO

INSERT INTO testschema.customers (LocationID, Name) VALUES
(3, N'Panasonic Corporation'), 
(29, N'Credit Suisse'), 
(44, N'Pampers'), 
(44, N'United Parcel Service'), 
(22, N'Nescafé'), 
(35, N'Intel Corporation'), 
(36, N'Citigroup'), 
(44, N'Global Gillette'), 
(48, N'H&M'), 
(44, N'Harley-Davidson Motor Company'), 
(39, N'Volkswagen Group'), 
(44, N'IBM'), 
(48, N'Oracle Corporation'), 
(48, N'Cisco Systems, Inc.'), 
(59, N'Johnnie Walker'), 
(21, N'Gucci'), 
(48, N'eBay'), 
(17, N'Johnson & Johnson'), 
(12, N'Sprite'), 
(8, N'Mitsubishi'), 
(25, N'Deere & Company'), 
(39, N'Cartier SA'), 
(39, N'Mercedes-Benz'), 
(48, N'MasterCard'), 
(17, N'Audi'), 
(9, N'McDonald''s'), 
(59, N'Jack Daniel''s'), 
(8, N'Sony'), 
(4, N'Louis Vuitton'), 
(21, N'IKEA'), 
(10, N'Samsung Group'), 
(8, N'Honda Motor Company, Ltd'), 
(24, N'Zara'), 
(32, N'Ralph Lauren Corporation'), 
(39, N'Porsche'), 
(37, N'Pizza Hut'), 
(47, N'Nike, Inc.'), 
(20, N'Nintendo'), 
(48, N'Facebook, Inc.'), 
(8, N'Nissan Motor Co., Ltd.'), 
(33, N'The Walt Disney Company'), 
(59, N'Microsoft'), 
(61, N'Beko'), 
(12, N'Moët et Chandon'), 
(44, N'Bank of America'), 
(44, N'Hewlett-Packard'), 
(8, N'Heineken Brewery'), 
(36, N'Nokia'), 
(48, N'Yahoo!'), 
(46, N'PepsiCo'), 
(50, N'Smirnoff'), 
(52, N'Wal-Mart'), 
(45, N'Ferrari S.p.A.'), 
(52, N'Hermès'), 
(52, N'NTT Data'), 
(48, N'Adobe Systems'), 
(45, N'Canon'), 
(44, N'Google'), 
(43, N'KFC'), 
(44, N'Chase'), 
(13, N'Corona'), 
(48, N'Home Depot'), 
(17, N'Kleenex'), 
(39, N'SAP'), 
(39, N'Vodafone'), 
(48, N'Apple Inc.'), 
(31, N'Budweiser Stag Brewing Company'), 
(41, N'VISA'), 
(41, N'Adidas'), 
(28, N'HSBC'), 
(54, N'Kia Motors'), 
(55, N'BlackBerry'), 
(17, N'Xerox'), 
(44, N'Verizon Communications'), 
(36, N'Amazon.com'), 
(21, N'Caterpillar Inc.'), 
(31, N'General Electric'), 
(27, N'American Express'), 
(48, N'Wells Fargo'), 
(17, N'Prada'), 
(59, N'Morgan Stanley'), 
(59, N'L''Oréal'), 
(39, N'Siemens AG'), 
(8, N'Toyota Motor Corporation'), 
(54, N'Hyundai'), 
(39, N'BMW'), 
(41, N'Starbucks'), 
(64, N'Tesco Corporation'), 
(25, N'AT&T'), 
(25, N'Shell Oil Company'), 
(44, N'Kellogg Company'), 
(48, N'MTV'), 
(44, N'Tiffany & Co.'), 
(59, N'Avon'), 
(18, N'Coca-Cola'), 
(26, N'Allianz'), 
(2, N'Gap Inc.'), 
(59, N'Burberry'), 
(13, N'3M'); 
GO


CREATE TABLE testschema.orders (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  EmployeeID INT NOT NULL,
  CustomerID INT NOT NULL,
  DateOrdered DateTime NOT NULL,
  DateShipped DateTime,
  Paid BIT NOT NULL DEFAULT(0)
);
GO

CREATE TABLE testschema.orderdetails (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  OrderID INT NOT NULL,
  Qty INT NOT NULL,
  MeasureID INT NOT NULL,
  Picked BIT NOT NULL DEFAULT(0)
);
GO

